spring.datasource.url=jdbc:h2:mem:flightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:685927881740-cvkrdcfehddfh9n7ale4ho3kv46tbp43.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}